### ISSUE TITLE
The requested URL /acc/Auth/login was not found on this server.

### ISSUE THREAD

**Issue by Dev168** [auwfar/AdminLTE-CRUD-With-Codeigniter#2]
Hi 
How to resolve ?

Not Found

The requested URL /acc/Auth/login was not found on this server.

Thanks ?

**Comment by auwfar** [comment]
Can you show me the screenshot?

Pada tanggal 16 Jun 2017 16.54, "โรเบิร์ต ทิงนองนอย" <
notifications@github.com> menulis:

**Comment by Dev168** [comment]
Screenshot

![screen shot 2560-06-16 at 5 16 55 pm](https://user-images.githubusercontent.com/21017375/27222557-eb22146e-52b6-11e7-8d1a-33262fe4c373.png)

**Comment by Dev168** [comment]
That is error result after login

**Comment by auwfar** [comment]
in windows, there is no error like that, maybe this link can solve your problem https://www.youtube.com/watch?v=UExwuaneFpg

**Comment by Dev168** [comment]
ok, Thanks.

**Comment by auwfar** [comment]
Your Welcome
