### ISSUE TITLE
Login not working, always redirect to http://localhost/crud-ci/Auth without error message

### ISSUE THREAD

**Issue by Freizello** [auwfar/AdminLTE-CRUD-With-Codeigniter#3]
Selalu redirect ke /Auth saat masukkan user dan password. Tidak ada pesan error atau keterangan salah password.

![image](https://user-images.githubusercontent.com/12061206/32038693-4ababee8-ba55-11e7-99cf-752fc44d4bf5.png)

**Comment by malikalichsan** [comment]
juga terjadi di Saya

**Comment by zdienos** [comment]
samaa

**Comment by hackidozone** [comment]
di saya malah error 404, di path http://localhost/template/Auth/login

**Comment by akangneo** [comment]
saya jg mengalamin hal yg sama seperti di atas,
tolong solusi nya

**Comment by febrianblo** [comment]
iya direct ke auth terus
gmana ya solusinya?

**Comment by deazure** [comment]
Hello ,
when i login i get error 404.
can you help.

**Comment by zainurieuis** [comment]
Hello everyone,
bagi yang tidak bisa login , masalahnya adalah karena bugs dari CI versi 3. 
saat ini sudah diperbaiki bugsnya. 

jadi solusinya: 
- download CI 3 dari websitenya
- extrak file nya
- hapus folder system yang ada di AdminLTE-CRUD-With-Codeigniter ini
- copy paste folder system dari file yang didownload dari CI terbaru

selamat mencoba.

**Comment by adamsinobo** [comment]
![image](https://user-images.githubusercontent.com/35942568/64412348-64ca0880-d0b9-11e9-800a-4866ef607c31.png)


hello?

mas tanya kenapa kalau saya nambahin admin lagi gak bisa buat login ya?
tapi kalau akun awfar sama ozil bisa
